### ISSUE TITLE
Add: README> 開発を開始> Docker daemonを立ち上げる旨を足す

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/devenv#1]
記載された通りに`docker-compose up`を実行した時、以下のようなエラーが出ました。

```
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```

`docker-machine start default`の実行をREADMEに書いておくべきであると思います。

**Comment by Cj-bc** [comment]
github-issue.vimが動かないのでcodehubから。

```
docker-machine star default
```

を実行した後、 `defaultが存在しません`的なことを言われて失敗しました。
docker初期設定についてまで書くべきなのかも…
まぁggレバいいのだけどもさ()

**Comment by coord-e** [comment]
それはwin/macの設定なので、それぞれについて詳しい手順を追記します

**Comment by coord-e** [comment]
Windows 32bitでdocker-machineを使う方法について追記しました。
あと`defaultが存在しません`は`docker-machine create default`すれば治りますがmacOSではDocker CEを使ってください。
