### ISSUE TITLE
Lintできない

### ISSUE THREAD

**Issue by coord-e** [Sakuten/devenv#13]
Lintするのにホスト側のマシンに環境構築を強いるのはよくない

```
docker-compose run --rm lint
```

こんなノリでLintできるようにしたい

**Comment by Cj-bc** [comment]
このLintというのは何に対しての？`devenv`のコードについてのもの??
そうでないならbackはできるけどなぁと思った次第

**Comment by coord-e** [comment]
できはするけど、それはホスト側で`pipenv run lint`走らせてるってことっしょ
すると開発機に`pipenv`インストールしてもらわなきゃいけなくなってくるし、Windowsだった時が悲惨なのでコンテナ内でLintしたい

**Comment by Cj-bc** [comment]
あ〜、なるほど？
確かにそうなのか...orz

**Comment by coord-e** [comment]
よく考えると、パッケージインストールもいちいちコンテナ再起動しなきゃいけなくてつらい

**Comment by coord-e** [comment]
これですが、テストもコンテナ化しないとあれなので

**Comment by coord-e** [comment]
単体で動くものは個別リポジトリへ、
dockerさえあればなんでも動くのがここ、っていう分類で行きます
つまりじきに各リポのDockerfile.devもこっちに来る(はず)
