### ISSUE TITLE
Git-flowについて明記

### ISSUE THREAD

**Issue by coord-e** [Sakuten/devenv#6]
`gitflow`本家は`git flow bugfix`がないので、`gitflow-avh`を使うよう明記
https://github.com/petervanderdoes/gitflow-avh

**Comment by Cj-bc** [comment]
そもそも、`git flow`を使用するように指示が出ていなかったことに気がついた..
その追加と、`git flow * finish`を行わないような指示もしたほうがいいと思う。
するとdevelopにマージされてしまうので

**Comment by coord-e** [comment]
まあマージしちゃってもpushできないけどな
了解です

**Comment by Cj-bc** [comment]
` push`出来ないのはそうなんだけど、`develop`にマージすると同時に元のブランチ消されちゃうので…（さっきやった）
明記よろしくです

**Comment by Cj-bc** [comment]
[#7](https://github.com/Sakuten/devenv/pull/7)

**Comment by Cj-bc** [comment]
対象のPR [#7](https://github.com/Sakuten/devenv/pull/7)がマージされたので閉じます
